deployment:
  tasks:
    - export DEPLOYPATH=/home/zksystem/
    - /bin/cp -r * $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
